version: "3.7"
services:
  nexus:
    image: sonatype/nexus3:3.1.0
    ports:
        - "8081:8081"
        container_name: nexus
        
sonarqube:
   image: sonarqube:7.8-community
   ports:
        - "9000:9000"
        container_name: sonarqube
        
 web:
   build: .
   ports:
       - "8080:8080"
        
