version: "3.7"
services:
  nexus:
    image: sonatype/nexus3
    ports: 
      - "8081:8081"
    container_name: nexus_acada
  sonarqube:
    image: sonarqube:lts-community
    ports: 
      - "9000:9000"
    container_name: sonarqube

  web:
    build: .
    ports:
      - "8080:8080"
